name: base
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - astroid=2.2.5
  - astropy=3.1.2
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - blaze=0.11.3
  - bleach=3.1.0
  - blosc=1.15.0
  - bokeh=1.0.4
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - chardet=3.0.4
  - click=7.0
  - cython=0.29.6
  - cytoolz=0.9.0.1
  - dask=1.1.4
  - dask-core=1.1.4
  - datashape=0.5.4
  - decorator=4.4.0
  - defusedxml=0.5.0
  - distributed=1.26.0
  - docutils=0.14
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fastcache=1.0.2
  - filelock=3.0.10
  - flask=1.0.2
  - flask-cors=3.0.7
  - freetype=2.9.1
  - future=0.17.1
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - glob2=0.6
  - greenlet=0.4.15
  - h5py=2.9.0
  - hdf5=1.10.4
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - imagesize=1.1.0
  - importlib_metadata=0.8
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - isort=4.3.16
  - jdcal=1.4
  - jpeg=9b
  - jsonschema=3.0.1
  - keyring=18.0.0
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libarchive=3.3.3
  - libcurl=7.64.0
  - libiconv=1.15
  - liblief=0.9.0
  - libpng=1.6.36
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.28.0
  - locket=0.2.0
  - lxml=4.3.2
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.3
  - mkl-service=1.1.2
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=6.0.0
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - networkx=2.2
  - nltk=3.4
  - nose=1.3.7
  - numba=0.43.1
  - numexpr=2.6.9
  - numpy=1.16.2
  - numpy-base=1.16.2
  - numpydoc=0.8.0
  - odo=0.5.1
  - olefile=0.46
  - openpyxl=2.6.1
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - partd=0.3.10
  - path.py=11.5.0
  - pathlib2=2.3.3
  - patsy=0.5.1
  - pep8=1.7.1
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - pkginfo=1.5.0.1
  - pluggy=0.9.0
  - ply=3.11
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.1
  - py=1.8.0
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.1.1
  - pygments=2.3.1
  - pylint=2.3.1
  - pyodbc=4.0.26
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - pytables=3.5.1
  - pytest=4.3.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.3.2
  - pytest-remotedata=0.3.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-libarchive-c=2.8
  - pytz=2018.9
  - pywavelets=1.0.2
  - pyyaml=5.1
  - pyzmq=18.0.0
  - requests=2.21.0
  - rope=0.12.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=1.2.1
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.8
  - sphinx=1.8.5
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlalchemy=1.3.1
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - sympy=1.3
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=6.0.2
  - tqdm=4.31.1
  - traitlets=4.3.2
  - unicodecsv=0.14.1
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - wrapt=1.11.1
  - xlrd=1.2.0
  - xlsxwriter=1.1.5
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=0.1.4
  - zipp=0.3.3
  - zlib=1.2.11
  - zstd=1.3.7
